AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patientcheckout

  Sample SAM Template for patientcheckout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  PatientCheckoutDLQ:
    Type: AWS::SNS::Topic
  StudentResultDLQ:
    Type: AWS::SNS::Topic  
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic

  StudentGradeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub studentgrade-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  StudentGradeTopic:
    Type: AWS::SNS::Topic  
   
     
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.sondhi.harsh.s3sns.lambda.PatientCheckoutLambda::checkoutLambdaHandler
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref PatientCheckoutDLQ
      Policies:
      - S3ReadPolicy:
          BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
      - SNSPublishMessagePolicy:
          TopicName: !GetAtt PatientCheckoutTopic.TopicName    
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*

  StudentGradeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.sondhi.harsh.s3sns.lambda.StudentReceiveGradesLambda::studentGradeLambdaHandler
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref StudentResultDLQ
      Policies:
      - S3ReadPolicy:
          BucketName: !Sub studentgrade-${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
      - SNSPublishMessagePolicy:
          TopicName: !GetAtt StudentGradeTopic.TopicName    
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          STUDENT_RESULT_TOPIC: !Ref StudentGradeTopic
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref  StudentGradeBucket
            Events: s3:ObjectCreated:*        




  BillManagementFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.sondhi.harsh.s3sns.lambda.BillManagementLambda::billManagementHandler
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopic      
  ResultPublishingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.sondhi.harsh.s3sns.lambda.ResultPublishLambda::resultPublishingHandler
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref StudentGradeTopic       
  ErrorHandlingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.sondhi.harsh.s3sns.errorhandling.ErrorHandler::deadletterSNSHandler
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutDLQ      
  StudentErrorHandlingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.sondhi.harsh.s3sns.errorhandling.StudentsErrorHandler::studentDeadletterSNSHandler
      Runtime: java11
      Architectures:
      - x86_64
      MemorySize: 512
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref StudentResultDLQ                              

  
